version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: salesapp-postgres
    environment:
      POSTGRES_USER: salesapp
      POSTGRES_PASSWORD: salesapp
      POSTGRES_DB: salesapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: salesapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

